### PR TITLE
Add support for procmail

### PR DESCRIPTION
**Pull request by pirzyk**

### CODE REVIEW

**Comment by vbotka** [comment]
Thank you for your contribution! I'll review the details soon.

**Comment by vbotka** [comment]
This should be implemented in freebsd_postinstall. See [tasks/procmail.yml](https://github.com/vbotka/ansible-freebsd-postinstall/blob/master/tasks/procmail.yml). Just add:

* defaults:
  * fp_procmail_rc_file: /usr/local/etc/procmailrc
  * fp_procmail_rc_config: []

* template 
* task

```yaml
- name: "procmail: Configure {{ fp_procmail_rc_file }}"
  template:
    dest: "{{ fp_procmail_rc_file }}"
    owner: root
    mode: '0644'
    src: procmailrc.j2
  vars:
    config: "{{ fp_procmail_rc_config }}"
  when: fp_procmail_rc_config|length > 0
  tags: fp_procmail_rc
```

* Add the tag to defaults/main/sanity.yml

What do you think?

**Comment by pirzyk** [comment]
For me it would not make much of a difference since I have both on my servers.  But I only use it on my mailserver, so that is why I had included it there and not in postinstall.  You may move it if you'd like.

**Comment by vbotka** [comment]
OK. I updated freebsd_postinstall tasks/procmail in devel and staging. By default, all actions are off in procmail.yml.

**Comment by pirzyk** [comment]
The procmailrc code in postinstall looks good.

**Pull request closed without merging**
