### PR TITLE
DKIM updates

### PR DESCRIPTION
**Pull request by pirzyk**
Added support to verify dkim config file
    Added support for non default DKIM selectors

### CODE REVIEW

**Comment by vbotka** [comment]
Thank you for your contribution! I'll review the details soon.

**Comment by vbotka** [comment]
In dkim.yml
* I fixed the missing defaults
* changed structure of fm_dkim_domains
* changed the labels to `{{ item.selector }} {{ item.name }}`
* set explicit `state=directory` of fm_dkim_run_dir

In dirs.yml
* changed item to item.name due to the changed structure of fm_dkim_domains

Now the play passes. Could you review the defaults?

Could you review the templates? For example, the paths of the private keys differ in the KeyTable.

I haven't tested the functionality. Could you test it?

**Comment by vbotka** [comment]
There seems to be a problem with the handler 'verify dkim'.

The below command parses the configuration file only. The files TrustedHosts, SigningTable, and KeyTable are not parsed (tested)

```bash
opendkim -x /usr/local/etc/opendkim/opendkim.conf -n
```
Consequently, the handler 'verify dkim' is useless and can be removed. The configuration of opendkim.conf should validate the configuration

```yaml
  validate: opendkim -x %s -n
```

**Comment by vbotka** [comment]
All known issues were fixed in the devel branch. It has not been tested yet.

**Comment by pirzyk** [comment]
Changes look good to me, no issues uncovered so far.

**Comment by vbotka** [comment]
Merged *devel* to *master* and tagged 2.5.0

JFYI, you're not listed among the contributors

https://github.com/vbotka/ansible-freebsd-mailserver/graphs/contributors

 Probably because your email is not associated with your GitHub profile?

**Comment by pirzyk** [comment]
So yea, there seems to be no easy way for me in .gitconfig to have multiple email addresses.  I use different email addresses based on the git server itself, my primary (internal) git server is the one I use the most so that is why that is the email I have assigned.

If you know of a way to have variable addresses based on which server git is talking to, I'm all ears.  Last time I looked was a few years ago.  It might have changed since then.

**Comment by vbotka** [comment]
> If you know of a way to have variable addresses based on which server git ...

`git commit` provides `-S[<keyid>]` to select address of GPG-sign commits. This is not server-based.

**Comment by pirzyk** [comment]
Found a solution, to use `includeIf` like this:
```
[includeIf "hasconfig:remote.*.url:git@github.com:*/**"]
    path = ~/.gitconfig.github
```

**Comment by vbotka** [comment]
I see. Nice! Thank you for sharing.

**Pull request merged**
